/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class AEaxRegister extends PRegister
{
    private TEax _eax_;

    public AEaxRegister()
    {
        // Constructor
    }

    public AEaxRegister(
        @SuppressWarnings("hiding") TEax _eax_)
    {
        // Constructor
        setEax(_eax_);

    }

    @Override
    public Object clone()
    {
        return new AEaxRegister(
            cloneNode(this._eax_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEaxRegister(this);
    }

    public TEax getEax()
    {
        return this._eax_;
    }

    public void setEax(TEax node)
    {
        if(this._eax_ != null)
        {
            this._eax_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eax_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eax_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eax_ == child)
        {
            this._eax_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eax_ == oldChild)
        {
            setEax((TEax) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
