/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class AEbpRegister extends PRegister
{
    private TEbp _ebp_;

    public AEbpRegister()
    {
        // Constructor
    }

    public AEbpRegister(
        @SuppressWarnings("hiding") TEbp _ebp_)
    {
        // Constructor
        setEbp(_ebp_);

    }

    @Override
    public Object clone()
    {
        return new AEbpRegister(
            cloneNode(this._ebp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEbpRegister(this);
    }

    public TEbp getEbp()
    {
        return this._ebp_;
    }

    public void setEbp(TEbp node)
    {
        if(this._ebp_ != null)
        {
            this._ebp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ebp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ebp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ebp_ == child)
        {
            this._ebp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ebp_ == oldChild)
        {
            setEbp((TEbp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
