/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class AEbxRegister extends PRegister
{
    private TEbx _ebx_;

    public AEbxRegister()
    {
        // Constructor
    }

    public AEbxRegister(
        @SuppressWarnings("hiding") TEbx _ebx_)
    {
        // Constructor
        setEbx(_ebx_);

    }

    @Override
    public Object clone()
    {
        return new AEbxRegister(
            cloneNode(this._ebx_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEbxRegister(this);
    }

    public TEbx getEbx()
    {
        return this._ebx_;
    }

    public void setEbx(TEbx node)
    {
        if(this._ebx_ != null)
        {
            this._ebx_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ebx_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ebx_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ebx_ == child)
        {
            this._ebx_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ebx_ == oldChild)
        {
            setEbx((TEbx) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
