/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class AEspRegister extends PRegister
{
    private TEsp _esp_;

    public AEspRegister()
    {
        // Constructor
    }

    public AEspRegister(
        @SuppressWarnings("hiding") TEsp _esp_)
    {
        // Constructor
        setEsp(_esp_);

    }

    @Override
    public Object clone()
    {
        return new AEspRegister(
            cloneNode(this._esp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEspRegister(this);
    }

    public TEsp getEsp()
    {
        return this._esp_;
    }

    public void setEsp(TEsp node)
    {
        if(this._esp_ != null)
        {
            this._esp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esp_ == child)
        {
            this._esp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esp_ == oldChild)
        {
            setEsp((TEsp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
