/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class ANotInst extends PInst
{
    private POplabel _oplabel_;
    private TNot _not_;
    private PAr _ar_;

    public ANotInst()
    {
        // Constructor
    }

    public ANotInst(
        @SuppressWarnings("hiding") POplabel _oplabel_,
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PAr _ar_)
    {
        // Constructor
        setOplabel(_oplabel_);

        setNot(_not_);

        setAr(_ar_);

    }

    @Override
    public Object clone()
    {
        return new ANotInst(
            cloneNode(this._oplabel_),
            cloneNode(this._not_),
            cloneNode(this._ar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotInst(this);
    }

    public POplabel getOplabel()
    {
        return this._oplabel_;
    }

    public void setOplabel(POplabel node)
    {
        if(this._oplabel_ != null)
        {
            this._oplabel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oplabel_ = node;
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PAr getAr()
    {
        return this._ar_;
    }

    public void setAr(PAr node)
    {
        if(this._ar_ != null)
        {
            this._ar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oplabel_)
            + toString(this._not_)
            + toString(this._ar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oplabel_ == child)
        {
            this._oplabel_ = null;
            return;
        }

        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._ar_ == child)
        {
            this._ar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oplabel_ == oldChild)
        {
            setOplabel((POplabel) newChild);
            return;
        }

        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._ar_ == oldChild)
        {
            setAr((PAr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
