/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class ARecLconst extends PLconst
{
    private PConst _const_;
    private PLconst _lconst_;

    public ARecLconst()
    {
        // Constructor
    }

    public ARecLconst(
        @SuppressWarnings("hiding") PConst _const_,
        @SuppressWarnings("hiding") PLconst _lconst_)
    {
        // Constructor
        setConst(_const_);

        setLconst(_lconst_);

    }

    @Override
    public Object clone()
    {
        return new ARecLconst(
            cloneNode(this._const_),
            cloneNode(this._lconst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecLconst(this);
    }

    public PConst getConst()
    {
        return this._const_;
    }

    public void setConst(PConst node)
    {
        if(this._const_ != null)
        {
            this._const_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._const_ = node;
    }

    public PLconst getLconst()
    {
        return this._lconst_;
    }

    public void setLconst(PLconst node)
    {
        if(this._lconst_ != null)
        {
            this._lconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lconst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._const_)
            + toString(this._lconst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._const_ == child)
        {
            this._const_ = null;
            return;
        }

        if(this._lconst_ == child)
        {
            this._lconst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._const_ == oldChild)
        {
            setConst((PConst) newChild);
            return;
        }

        if(this._lconst_ == oldChild)
        {
            setLconst((PLconst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
