/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TBss extends Token
{
    public TBss()
    {
        super.setText(".bss");
    }

    public TBss(int line, int pos)
    {
        super.setText(".bss");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBss(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBss(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBss text.");
    }
}
