/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TData extends Token
{
    public TData()
    {
        super.setText(".data");
    }

    public TData(int line, int pos)
    {
        super.setText(".data");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TData(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTData(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TData text.");
    }
}
