/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TDefineword extends Token
{
    public TDefineword()
    {
        super.setText("dw");
    }

    public TDefineword(int line, int pos)
    {
        super.setText("dw");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefineword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefineword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefineword text.");
    }
}
