/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TDefinebyte extends Token
{
    public TDefinebyte()
    {
        super.setText("db");
    }

    public TDefinebyte(int line, int pos)
    {
        super.setText("db");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefinebyte(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefinebyte(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefinebyte text.");
    }
}
