/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TDefinetenbytes extends Token
{
    public TDefinetenbytes()
    {
        super.setText("dt");
    }

    public TDefinetenbytes(int line, int pos)
    {
        super.setText("dt");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefinetenbytes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefinetenbytes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefinetenbytes text.");
    }
}
