/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TEbx extends Token
{
    public TEbx()
    {
        super.setText("ebx");
    }

    public TEbx(int line, int pos)
    {
        super.setText("ebx");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEbx(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEbx(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEbx text.");
    }
}
