/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TEdx extends Token
{
    public TEdx()
    {
        super.setText("edx");
    }

    public TEdx(int line, int pos)
    {
        super.setText("edx");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEdx(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEdx(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEdx text.");
    }
}
