/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TGlobal extends Token
{
    public TGlobal()
    {
        super.setText("global");
    }

    public TGlobal(int line, int pos)
    {
        super.setText("global");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGlobal(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGlobal(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGlobal text.");
    }
}
