/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TIdiv extends Token
{
    public TIdiv()
    {
        super.setText("idiv");
    }

    public TIdiv(int line, int pos)
    {
        super.setText("idiv");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdiv(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdiv(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIdiv text.");
    }
}
