/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TInc extends Token
{
    public TInc()
    {
        super.setText("include");
    }

    public TInc(int line, int pos)
    {
        super.setText("include");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInc text.");
    }
}
