/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TJl extends Token
{
    public TJl()
    {
        super.setText("jl");
    }

    public TJl(int line, int pos)
    {
        super.setText("jl");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TJl(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TJl text.");
    }
}
