/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TJne extends Token
{
    public TJne()
    {
        super.setText("jne");
    }

    public TJne(int line, int pos)
    {
        super.setText("jne");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TJne(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJne(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TJne text.");
    }
}
