/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TReservebyte extends Token
{
    public TReservebyte()
    {
        super.setText("resb");
    }

    public TReservebyte(int line, int pos)
    {
        super.setText("resb");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReservebyte(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReservebyte(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReservebyte text.");
    }
}
