/* This file was generated by SableCC (http://www.sablecc.org/). */

package nasmParser.node;

import nasmParser.analysis.*;

@SuppressWarnings("nls")
public final class TReservedoubleword extends Token
{
    public TReservedoubleword()
    {
        super.setText("resd");
    }

    public TReservedoubleword(int line, int pos)
    {
        super.setText("resd");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReservedoubleword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReservedoubleword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReservedoubleword text.");
    }
}
