/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class AAppelInst extends PInst
{
    private PAppel _appel_;

    public AAppelInst()
    {
        // Constructor
    }

    public AAppelInst(
        @SuppressWarnings("hiding") PAppel _appel_)
    {
        // Constructor
        setAppel(_appel_);

    }

    @Override
    public Object clone()
    {
        return new AAppelInst(
            cloneNode(this._appel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelInst(this);
    }

    public PAppel getAppel()
    {
        return this._appel_;
    }

    public void setAppel(PAppel node)
    {
        if(this._appel_ != null)
        {
            this._appel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._appel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._appel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._appel_ == child)
        {
            this._appel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._appel_ == oldChild)
        {
            setAppel((PAppel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
