/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class AAppelExp extends PExp
{
    private TPo _po_;
    private TSaexpappel _saexpappel_;
    private PAppel _appel_;
    private TPf _pf_;

    public AAppelExp()
    {
        // Constructor
    }

    public AAppelExp(
        @SuppressWarnings("hiding") TPo _po_,
        @SuppressWarnings("hiding") TSaexpappel _saexpappel_,
        @SuppressWarnings("hiding") PAppel _appel_,
        @SuppressWarnings("hiding") TPf _pf_)
    {
        // Constructor
        setPo(_po_);

        setSaexpappel(_saexpappel_);

        setAppel(_appel_);

        setPf(_pf_);

    }

    @Override
    public Object clone()
    {
        return new AAppelExp(
            cloneNode(this._po_),
            cloneNode(this._saexpappel_),
            cloneNode(this._appel_),
            cloneNode(this._pf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelExp(this);
    }

    public TPo getPo()
    {
        return this._po_;
    }

    public void setPo(TPo node)
    {
        if(this._po_ != null)
        {
            this._po_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._po_ = node;
    }

    public TSaexpappel getSaexpappel()
    {
        return this._saexpappel_;
    }

    public void setSaexpappel(TSaexpappel node)
    {
        if(this._saexpappel_ != null)
        {
            this._saexpappel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._saexpappel_ = node;
    }

    public PAppel getAppel()
    {
        return this._appel_;
    }

    public void setAppel(PAppel node)
    {
        if(this._appel_ != null)
        {
            this._appel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._appel_ = node;
    }

    public TPf getPf()
    {
        return this._pf_;
    }

    public void setPf(TPf node)
    {
        if(this._pf_ != null)
        {
            this._pf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._po_)
            + toString(this._saexpappel_)
            + toString(this._appel_)
            + toString(this._pf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._po_ == child)
        {
            this._po_ = null;
            return;
        }

        if(this._saexpappel_ == child)
        {
            this._saexpappel_ = null;
            return;
        }

        if(this._appel_ == child)
        {
            this._appel_ = null;
            return;
        }

        if(this._pf_ == child)
        {
            this._pf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._po_ == oldChild)
        {
            setPo((TPo) newChild);
            return;
        }

        if(this._saexpappel_ == oldChild)
        {
            setSaexpappel((TSaexpappel) newChild);
            return;
        }

        if(this._appel_ == oldChild)
        {
            setAppel((PAppel) newChild);
            return;
        }

        if(this._pf_ == oldChild)
        {
            setPf((TPf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
