/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class AProg extends PProg
{
    private TPo _po_;
    private TSaprog _saprog_;
    private PLdecvar _ldecvar_;
    private PLdecfonc _ldecfonc_;
    private TPf _pf_;

    public AProg()
    {
        // Constructor
    }

    public AProg(
        @SuppressWarnings("hiding") TPo _po_,
        @SuppressWarnings("hiding") TSaprog _saprog_,
        @SuppressWarnings("hiding") PLdecvar _ldecvar_,
        @SuppressWarnings("hiding") PLdecfonc _ldecfonc_,
        @SuppressWarnings("hiding") TPf _pf_)
    {
        // Constructor
        setPo(_po_);

        setSaprog(_saprog_);

        setLdecvar(_ldecvar_);

        setLdecfonc(_ldecfonc_);

        setPf(_pf_);

    }

    @Override
    public Object clone()
    {
        return new AProg(
            cloneNode(this._po_),
            cloneNode(this._saprog_),
            cloneNode(this._ldecvar_),
            cloneNode(this._ldecfonc_),
            cloneNode(this._pf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProg(this);
    }

    public TPo getPo()
    {
        return this._po_;
    }

    public void setPo(TPo node)
    {
        if(this._po_ != null)
        {
            this._po_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._po_ = node;
    }

    public TSaprog getSaprog()
    {
        return this._saprog_;
    }

    public void setSaprog(TSaprog node)
    {
        if(this._saprog_ != null)
        {
            this._saprog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._saprog_ = node;
    }

    public PLdecvar getLdecvar()
    {
        return this._ldecvar_;
    }

    public void setLdecvar(PLdecvar node)
    {
        if(this._ldecvar_ != null)
        {
            this._ldecvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldecvar_ = node;
    }

    public PLdecfonc getLdecfonc()
    {
        return this._ldecfonc_;
    }

    public void setLdecfonc(PLdecfonc node)
    {
        if(this._ldecfonc_ != null)
        {
            this._ldecfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldecfonc_ = node;
    }

    public TPf getPf()
    {
        return this._pf_;
    }

    public void setPf(TPf node)
    {
        if(this._pf_ != null)
        {
            this._pf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._po_)
            + toString(this._saprog_)
            + toString(this._ldecvar_)
            + toString(this._ldecfonc_)
            + toString(this._pf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._po_ == child)
        {
            this._po_ = null;
            return;
        }

        if(this._saprog_ == child)
        {
            this._saprog_ = null;
            return;
        }

        if(this._ldecvar_ == child)
        {
            this._ldecvar_ = null;
            return;
        }

        if(this._ldecfonc_ == child)
        {
            this._ldecfonc_ = null;
            return;
        }

        if(this._pf_ == child)
        {
            this._pf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._po_ == oldChild)
        {
            setPo((TPo) newChild);
            return;
        }

        if(this._saprog_ == oldChild)
        {
            setSaprog((TSaprog) newChild);
            return;
        }

        if(this._ldecvar_ == oldChild)
        {
            setLdecvar((PLdecvar) newChild);
            return;
        }

        if(this._ldecfonc_ == oldChild)
        {
            setLdecfonc((PLdecfonc) newChild);
            return;
        }

        if(this._pf_ == oldChild)
        {
            setPf((TPf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
