/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TEntier extends Token
{
    public TEntier()
    {
        super.setText("entier");
    }

    public TEntier(int line, int pos)
    {
        super.setText("entier");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEntier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEntier text.");
    }
}
