/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TNul extends Token
{
    public TNul()
    {
        super.setText("nul");
    }

    public TNul(int line, int pos)
    {
        super.setText("nul");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNul(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNul(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNul text.");
    }
}
