/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSadecvarsimple extends Token
{
    public TSadecvarsimple()
    {
        super.setText("SaDecVarSimple");
    }

    public TSadecvarsimple(int line, int pos)
    {
        super.setText("SaDecVarSimple");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSadecvarsimple(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSadecvarsimple(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSadecvarsimple text.");
    }
}
