/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSadectab extends Token
{
    public TSadectab()
    {
        super.setText("SaDecTab");
    }

    public TSadectab(int line, int pos)
    {
        super.setText("SaDecTab");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSadectab(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSadectab(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSadectab text.");
    }
}
