/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSaexpfaux extends Token
{
    public TSaexpfaux()
    {
        super.setText("SaExpFaux");
    }

    public TSaexpfaux(int line, int pos)
    {
        super.setText("SaExpFaux");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSaexpfaux(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSaexpfaux(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSaexpfaux text.");
    }
}
