/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSaexpmodulo extends Token
{
    public TSaexpmodulo()
    {
        super.setText("SaExpModulo");
    }

    public TSaexpmodulo(int line, int pos)
    {
        super.setText("SaExpModulo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSaexpmodulo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSaexpmodulo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSaexpmodulo text.");
    }
}
