/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSaexpappel extends Token
{
    public TSaexpappel()
    {
        super.setText("SaExpAppel");
    }

    public TSaexpappel(int line, int pos)
    {
        super.setText("SaExpAppel");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSaexpappel(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSaexpappel(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSaexpappel text.");
    }
}
