/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSainsttantque extends Token
{
    public TSainsttantque()
    {
        super.setText("SaInstTantQue");
    }

    public TSainsttantque(int line, int pos)
    {
        super.setText("SaInstTantQue");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSainsttantque(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSainsttantque(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSainsttantque text.");
    }
}
