/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSainstaffect extends Token
{
    public TSainstaffect()
    {
        super.setText("SaInstAffect");
    }

    public TSainstaffect(int line, int pos)
    {
        super.setText("SaInstAffect");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSainstaffect(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSainstaffect(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSainstaffect text.");
    }
}
