/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSainstretour extends Token
{
    public TSainstretour()
    {
        super.setText("SaInstRetour");
    }

    public TSainstretour(int line, int pos)
    {
        super.setText("SaInstRetour");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSainstretour(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSainstretour(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSainstretour text.");
    }
}
