/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSainstbloc extends Token
{
    public TSainstbloc()
    {
        super.setText("SaInstBloc");
    }

    public TSainstbloc(int line, int pos)
    {
        super.setText("SaInstBloc");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSainstbloc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSainstbloc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSainstbloc text.");
    }
}
