/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSalexp extends Token
{
    public TSalexp()
    {
        super.setText("SaLExp");
    }

    public TSalexp(int line, int pos)
    {
        super.setText("SaLExp");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSalexp(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSalexp(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSalexp text.");
    }
}
