/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSaldecvar extends Token
{
    public TSaldecvar()
    {
        super.setText("SaLDecVar");
    }

    public TSaldecvar(int line, int pos)
    {
        super.setText("SaLDecVar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSaldecvar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSaldecvar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSaldecvar text.");
    }
}
