/* This file was generated by SableCC (http://www.sablecc.org/). */

package saParser.node;

import saParser.analysis.*;

@SuppressWarnings("nls")
public final class TSaprog extends Token
{
    public TSaprog()
    {
        super.setText("SaProg");
    }

    public TSaprog(int line, int pos)
    {
        super.setText("SaProg");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSaprog(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSaprog(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSaprog text.");
    }
}
