/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.parser;

import c3aParser.node.*;
import c3aParser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTCo(@SuppressWarnings("unused") TCo node)
    {
        this.index = 0;
    }

    @Override
    public void caseTCf(@SuppressWarnings("unused") TCf node)
    {
        this.index = 1;
    }

    @Override
    public void caseTCall(@SuppressWarnings("unused") TCall node)
    {
        this.index = 2;
    }

    @Override
    public void caseTStop(@SuppressWarnings("unused") TStop node)
    {
        this.index = 3;
    }

    @Override
    public void caseTFbegin(@SuppressWarnings("unused") TFbegin node)
    {
        this.index = 4;
    }

    @Override
    public void caseTFend(@SuppressWarnings("unused") TFend node)
    {
        this.index = 5;
    }

    @Override
    public void caseTAff(@SuppressWarnings("unused") TAff node)
    {
        this.index = 6;
    }

    @Override
    public void caseTNoteq(@SuppressWarnings("unused") TNoteq node)
    {
        this.index = 7;
    }

    @Override
    public void caseTInf(@SuppressWarnings("unused") TInf node)
    {
        this.index = 8;
    }

    @Override
    public void caseTInfeq(@SuppressWarnings("unused") TInfeq node)
    {
        this.index = 9;
    }

    @Override
    public void caseTSup(@SuppressWarnings("unused") TSup node)
    {
        this.index = 10;
    }

    @Override
    public void caseTSupeq(@SuppressWarnings("unused") TSupeq node)
    {
        this.index = 11;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 12;
    }

    @Override
    public void caseTGoto(@SuppressWarnings("unused") TGoto node)
    {
        this.index = 13;
    }

    @Override
    public void caseTParam(@SuppressWarnings("unused") TParam node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRet(@SuppressWarnings("unused") TRet node)
    {
        this.index = 15;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 16;
    }

    @Override
    public void caseTMoins(@SuppressWarnings("unused") TMoins node)
    {
        this.index = 17;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 18;
    }

    @Override
    public void caseTFois(@SuppressWarnings("unused") TFois node)
    {
        this.index = 19;
    }

    @Override
    public void caseTDivise(@SuppressWarnings("unused") TDivise node)
    {
        this.index = 20;
    }

    @Override
    public void caseTWrite(@SuppressWarnings("unused") TWrite node)
    {
        this.index = 21;
    }

    @Override
    public void caseTRead(@SuppressWarnings("unused") TRead node)
    {
        this.index = 22;
    }

    @Override
    public void caseTNombre(@SuppressWarnings("unused") TNombre node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPrefixeTemp(@SuppressWarnings("unused") TPrefixeTemp node)
    {
        this.index = 24;
    }

    @Override
    public void caseTIdentif(@SuppressWarnings("unused") TIdentif node)
    {
        this.index = 25;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 26;
    }
}
