/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AEnd extends PEnd
{
    private PEtiqop _etiqop_;
    private TFend _fend_;

    public AEnd()
    {
        // Constructor
    }

    public AEnd(
        @SuppressWarnings("hiding") PEtiqop _etiqop_,
        @SuppressWarnings("hiding") TFend _fend_)
    {
        // Constructor
        setEtiqop(_etiqop_);

        setFend(_fend_);

    }

    @Override
    public Object clone()
    {
        return new AEnd(
            cloneNode(this._etiqop_),
            cloneNode(this._fend_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnd(this);
    }

    public PEtiqop getEtiqop()
    {
        return this._etiqop_;
    }

    public void setEtiqop(PEtiqop node)
    {
        if(this._etiqop_ != null)
        {
            this._etiqop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._etiqop_ = node;
    }

    public TFend getFend()
    {
        return this._fend_;
    }

    public void setFend(TFend node)
    {
        if(this._fend_ != null)
        {
            this._fend_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fend_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._etiqop_)
            + toString(this._fend_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._etiqop_ == child)
        {
            this._etiqop_ = null;
            return;
        }

        if(this._fend_ == child)
        {
            this._fend_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._etiqop_ == oldChild)
        {
            setEtiqop((PEtiqop) newChild);
            return;
        }

        if(this._fend_ == oldChild)
        {
            setFend((TFend) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
