/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AFcall extends PFcall
{
    private PEtiqop _etiqop_;
    private PTv _result_;
    private TAff _aff_;
    private TCall _call_;
    private TIdentif _identif_;

    public AFcall()
    {
        // Constructor
    }

    public AFcall(
        @SuppressWarnings("hiding") PEtiqop _etiqop_,
        @SuppressWarnings("hiding") PTv _result_,
        @SuppressWarnings("hiding") TAff _aff_,
        @SuppressWarnings("hiding") TCall _call_,
        @SuppressWarnings("hiding") TIdentif _identif_)
    {
        // Constructor
        setEtiqop(_etiqop_);

        setResult(_result_);

        setAff(_aff_);

        setCall(_call_);

        setIdentif(_identif_);

    }

    @Override
    public Object clone()
    {
        return new AFcall(
            cloneNode(this._etiqop_),
            cloneNode(this._result_),
            cloneNode(this._aff_),
            cloneNode(this._call_),
            cloneNode(this._identif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFcall(this);
    }

    public PEtiqop getEtiqop()
    {
        return this._etiqop_;
    }

    public void setEtiqop(PEtiqop node)
    {
        if(this._etiqop_ != null)
        {
            this._etiqop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._etiqop_ = node;
    }

    public PTv getResult()
    {
        return this._result_;
    }

    public void setResult(PTv node)
    {
        if(this._result_ != null)
        {
            this._result_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._result_ = node;
    }

    public TAff getAff()
    {
        return this._aff_;
    }

    public void setAff(TAff node)
    {
        if(this._aff_ != null)
        {
            this._aff_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aff_ = node;
    }

    public TCall getCall()
    {
        return this._call_;
    }

    public void setCall(TCall node)
    {
        if(this._call_ != null)
        {
            this._call_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._call_ = node;
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._etiqop_)
            + toString(this._result_)
            + toString(this._aff_)
            + toString(this._call_)
            + toString(this._identif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._etiqop_ == child)
        {
            this._etiqop_ = null;
            return;
        }

        if(this._result_ == child)
        {
            this._result_ = null;
            return;
        }

        if(this._aff_ == child)
        {
            this._aff_ = null;
            return;
        }

        if(this._call_ == child)
        {
            this._call_ = null;
            return;
        }

        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._etiqop_ == oldChild)
        {
            setEtiqop((PEtiqop) newChild);
            return;
        }

        if(this._result_ == oldChild)
        {
            setResult((PTv) newChild);
            return;
        }

        if(this._aff_ == oldChild)
        {
            setAff((TAff) newChild);
            return;
        }

        if(this._call_ == oldChild)
        {
            setCall((TCall) newChild);
            return;
        }

        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
