/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AJmpsupInst extends PInst
{
    private PJmpsup _jmpsup_;

    public AJmpsupInst()
    {
        // Constructor
    }

    public AJmpsupInst(
        @SuppressWarnings("hiding") PJmpsup _jmpsup_)
    {
        // Constructor
        setJmpsup(_jmpsup_);

    }

    @Override
    public Object clone()
    {
        return new AJmpsupInst(
            cloneNode(this._jmpsup_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJmpsupInst(this);
    }

    public PJmpsup getJmpsup()
    {
        return this._jmpsup_;
    }

    public void setJmpsup(PJmpsup node)
    {
        if(this._jmpsup_ != null)
        {
            this._jmpsup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._jmpsup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._jmpsup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._jmpsup_ == child)
        {
            this._jmpsup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._jmpsup_ == oldChild)
        {
            setJmpsup((PJmpsup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
