/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AJmpinfInst extends PInst
{
    private PJmpinf _jmpinf_;

    public AJmpinfInst()
    {
        // Constructor
    }

    public AJmpinfInst(
        @SuppressWarnings("hiding") PJmpinf _jmpinf_)
    {
        // Constructor
        setJmpinf(_jmpinf_);

    }

    @Override
    public Object clone()
    {
        return new AJmpinfInst(
            cloneNode(this._jmpinf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJmpinfInst(this);
    }

    public PJmpinf getJmpinf()
    {
        return this._jmpinf_;
    }

    public void setJmpinf(PJmpinf node)
    {
        if(this._jmpinf_ != null)
        {
            this._jmpinf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._jmpinf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._jmpinf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._jmpinf_ == child)
        {
            this._jmpinf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._jmpinf_ == oldChild)
        {
            setJmpinf((PJmpinf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
