/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AJmpnegInst extends PInst
{
    private PJmpneg _jmpneg_;

    public AJmpnegInst()
    {
        // Constructor
    }

    public AJmpnegInst(
        @SuppressWarnings("hiding") PJmpneg _jmpneg_)
    {
        // Constructor
        setJmpneg(_jmpneg_);

    }

    @Override
    public Object clone()
    {
        return new AJmpnegInst(
            cloneNode(this._jmpneg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJmpnegInst(this);
    }

    public PJmpneg getJmpneg()
    {
        return this._jmpneg_;
    }

    public void setJmpneg(PJmpneg node)
    {
        if(this._jmpneg_ != null)
        {
            this._jmpneg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._jmpneg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._jmpneg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._jmpneg_ == child)
        {
            this._jmpneg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._jmpneg_ == oldChild)
        {
            setJmpneg((PJmpneg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
