/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AMulInst extends PInst
{
    private PMul _mul_;

    public AMulInst()
    {
        // Constructor
    }

    public AMulInst(
        @SuppressWarnings("hiding") PMul _mul_)
    {
        // Constructor
        setMul(_mul_);

    }

    @Override
    public Object clone()
    {
        return new AMulInst(
            cloneNode(this._mul_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMulInst(this);
    }

    public PMul getMul()
    {
        return this._mul_;
    }

    public void setMul(PMul node)
    {
        if(this._mul_ != null)
        {
            this._mul_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mul_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mul_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mul_ == child)
        {
            this._mul_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mul_ == oldChild)
        {
            setMul((PMul) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
