/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AProg extends PProg
{
    private PListeinst _listeinst_;

    public AProg()
    {
        // Constructor
    }

    public AProg(
        @SuppressWarnings("hiding") PListeinst _listeinst_)
    {
        // Constructor
        setListeinst(_listeinst_);

    }

    @Override
    public Object clone()
    {
        return new AProg(
            cloneNode(this._listeinst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProg(this);
    }

    public PListeinst getListeinst()
    {
        return this._listeinst_;
    }

    public void setListeinst(PListeinst node)
    {
        if(this._listeinst_ != null)
        {
            this._listeinst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeinst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listeinst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listeinst_ == child)
        {
            this._listeinst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listeinst_ == oldChild)
        {
            setListeinst((PListeinst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
