/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class ARecursifListeinst extends PListeinst
{
    private PInst _inst_;
    private PListeinst _listeinst_;

    public ARecursifListeinst()
    {
        // Constructor
    }

    public ARecursifListeinst(
        @SuppressWarnings("hiding") PInst _inst_,
        @SuppressWarnings("hiding") PListeinst _listeinst_)
    {
        // Constructor
        setInst(_inst_);

        setListeinst(_listeinst_);

    }

    @Override
    public Object clone()
    {
        return new ARecursifListeinst(
            cloneNode(this._inst_),
            cloneNode(this._listeinst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecursifListeinst(this);
    }

    public PInst getInst()
    {
        return this._inst_;
    }

    public void setInst(PInst node)
    {
        if(this._inst_ != null)
        {
            this._inst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inst_ = node;
    }

    public PListeinst getListeinst()
    {
        return this._listeinst_;
    }

    public void setListeinst(PListeinst node)
    {
        if(this._listeinst_ != null)
        {
            this._listeinst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeinst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inst_)
            + toString(this._listeinst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inst_ == child)
        {
            this._inst_ = null;
            return;
        }

        if(this._listeinst_ == child)
        {
            this._listeinst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inst_ == oldChild)
        {
            setInst((PInst) newChild);
            return;
        }

        if(this._listeinst_ == oldChild)
        {
            setListeinst((PListeinst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
