/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AReturn extends PReturn
{
    private PEtiqop _etiqop_;
    private TRet _ret_;
    private PCtv _ctv_;

    public AReturn()
    {
        // Constructor
    }

    public AReturn(
        @SuppressWarnings("hiding") PEtiqop _etiqop_,
        @SuppressWarnings("hiding") TRet _ret_,
        @SuppressWarnings("hiding") PCtv _ctv_)
    {
        // Constructor
        setEtiqop(_etiqop_);

        setRet(_ret_);

        setCtv(_ctv_);

    }

    @Override
    public Object clone()
    {
        return new AReturn(
            cloneNode(this._etiqop_),
            cloneNode(this._ret_),
            cloneNode(this._ctv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturn(this);
    }

    public PEtiqop getEtiqop()
    {
        return this._etiqop_;
    }

    public void setEtiqop(PEtiqop node)
    {
        if(this._etiqop_ != null)
        {
            this._etiqop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._etiqop_ = node;
    }

    public TRet getRet()
    {
        return this._ret_;
    }

    public void setRet(TRet node)
    {
        if(this._ret_ != null)
        {
            this._ret_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ret_ = node;
    }

    public PCtv getCtv()
    {
        return this._ctv_;
    }

    public void setCtv(PCtv node)
    {
        if(this._ctv_ != null)
        {
            this._ctv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ctv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._etiqop_)
            + toString(this._ret_)
            + toString(this._ctv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._etiqop_ == child)
        {
            this._etiqop_ = null;
            return;
        }

        if(this._ret_ == child)
        {
            this._ret_ = null;
            return;
        }

        if(this._ctv_ == child)
        {
            this._ctv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._etiqop_ == oldChild)
        {
            setEtiqop((PEtiqop) newChild);
            return;
        }

        if(this._ret_ == oldChild)
        {
            setRet((TRet) newChild);
            return;
        }

        if(this._ctv_ == oldChild)
        {
            setCtv((PCtv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
