/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class AStopInst extends PInst
{
    private PIstop _istop_;

    public AStopInst()
    {
        // Constructor
    }

    public AStopInst(
        @SuppressWarnings("hiding") PIstop _istop_)
    {
        // Constructor
        setIstop(_istop_);

    }

    @Override
    public Object clone()
    {
        return new AStopInst(
            cloneNode(this._istop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStopInst(this);
    }

    public PIstop getIstop()
    {
        return this._istop_;
    }

    public void setIstop(PIstop node)
    {
        if(this._istop_ != null)
        {
            this._istop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._istop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._istop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._istop_ == child)
        {
            this._istop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._istop_ == oldChild)
        {
            setIstop((PIstop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
