/* This file was generated by SableCC (http://www.sablecc.org/). */

package c3aParser.node;

import c3aParser.analysis.*;

@SuppressWarnings("nls")
public final class TFend extends Token
{
    public TFend()
    {
        super.setText("fend");
    }

    public TFend(int line, int pos)
    {
        super.setText("fend");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFend(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFend(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFend text.");
    }
}
